patched IBE hashToCurve with ietf hashToField impl
drand/tlock-js pull request #12
Opened 2022-12-21 16:01 UTC by CluEleSsUK

- pulled some pieces out of noble
- wrote an implementation of `hashToField` using https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-16#section-5.2
- created a patched `hashToCurve`

2022-12-21 16:03 UTC, CluEleSsUK commented
Took a first crack at this - only 3 tests failing including the go compatibility ones

2022-12-21 17:05 UTC, nikkolasg commented
What's the reason of having our own implementation of that ?
Noble seems to support the RFC too. is the difference in version the reason ? (12 for Noble vs 16 for this PR).

2022-12-21 17:15 UTC, CluEleSsUK commented
In retrospect, I perhaps should have read the feedback from the audit more clearly - it looks like only the rejection sampling in `h3` needs changed, not the whole hashToField x) I took the recommendation at the end to implement the ietf one a bit too literally oops

2022-12-21 17:51 UTC, AnomalRoil commented
Yeah, in theory Noble should implement what we need already.

2022-12-21 17:53 UTC, nikkolasg commented
Can someone link then the reason and/or issue raised in the audit (or paste a summary etc), in this PR or issue here ? It'd be nice that this PR contains everything one needs to know to understand the reasons, impacts etc.

2022-12-21 17:55 UTC, AnomalRoil commented
Our H3 function is vulnerable to collision. But I'd argue it's not a problem since we do key-wrapping and keys have fixed sizes, but TBH, using HashToField and HashToField from the RFC is probably better

2023-01-04 15:00 UTC, AnomalRoil requested changes
Could we switch to the Noble implementations? If you want to wrap them in your own function to change their API, that's fine.
Also let's keep the tests.

2023-01-04 15:02 UTC, CluEleSsUK commented on src/crypto/hash-to-curve.ts
> +export async function hashToCurve(input: Uint8Array | string): Promise<PointG2> {
we were actually using them already internally - I think we can just update the package and then change our h3 to comply

2023-01-04 15:03 UTC, CluEleSsUK commented
Closing this because I got the wrong end of the stick (was a good learning exercise though ;p)

2023-01-04 15:03 UTC, closed without merging